config/routes.rb
Rails.application.routes.draw do

  resources :article_sources

  resources :course_assignments do
    resources :assignment_responses
  end

  resources :course_periods
  get 'academic_terms' => 'course_periods#index'

  resources :course_sessions  do  
    resources :course_meetings
  end

  get 'my_sessions' => 'course_sessions#my_course_sessions', :as => :my_sessions

  resources :course_categories
  resources :courses

  resources :course_packets
  get 'resources' => 'course_packets#resources'  

  resources :discussion_questions do
      resources :discussion_responses
  end 
  
  resources :books do
    member do
      get :questions
    end
  end
  get 'index_table' => 'books#index_table', :as => :index_table

  resources :articles

  resources :book_categories
  get 'categories_table' => 'book_categories#table_index', :as => :categories_table

  resources :book_lists,       only: [:create, :destroy]
  resources :article_lists,       only: [:create, :destroy]
  resources :read_books,       only: [:create, :destroy]

  resources :users
  get 'register'  => 'users#new'
  get 'student_list' => 'users#student_list', :as => :student_list  
  get 'admin_list' => 'users#admin_list', :as => :admin_list
  get 'alumni_list' => 'users#alumni_list', :as => :alumni_list

  get 'my_courses' => 'users#course_list', :as => :my_courses

  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :account_activations, only: [:edit]

  resources :password_resets

  resources :users do
    resources :assessments
    member do
      get :following, :followers
      get :book_responses
      get :article_responses
      get 'my_instructors' => "users#my_instructor_list", :as => :my_instructors
      get 'my_students' => "users#my_student_list", :as => :my_students
      get 'books' => 'users#user_books', :as => :books
      get 'articles' => 'users#user_articles', :as => :articles
      get :edit_profile
      put :update_profile
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :advisor_relationships,       only: [:create, :destroy]

 resources :users do
    member do
      get :activate
    end
  end

  get '/about'    => 'high_voltage/pages#show', id: 'about'
  get '/contact'  => 'high_voltage/pages#show', id: 'contact'
  get '/privacy'  => 'high_voltage/pages#show', id: 'privacy'
  get '/terms'    => 'high_voltage/pages#show', id: 'terms'
  get '/team'    => 'high_voltage/pages#show', id: 'team'
  get '/student_portal'    => 'high_voltage/pages#show', id: 'student_portal'
  get '/admin_portal'    => 'high_voltage/pages#show', id: 'admin_portal'
  get '/community' => 'high_voltage/pages#show', id: 'community'
  get '/policies' => 'high_voltage/pages#show', id: 'policies'
  get '/zoom' => 'high_voltage/pages#show', id: 'zoom'
  get '/zoom_tour' => 'high_voltage/pages#show', id: 'zoom_tour'
  get '/zoom_tips' => 'high_voltage/pages#show', id: 'zoom_tips'

  get '/home', to: redirect('/')
  root :to => 'high_voltage/pages#show', id: 'home'

  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

app/models/assessment.rb
class Assessment < ActiveRecord::Base

	validates_presence_of :user_id
	#lifted this to allow reading assessments, :course_session_id

	belongs_to :user
	belongs_to :course_session



end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  before_action :set_assessment, only: [:show, :edit, :update, :destroy]
  
  before_filter :require_login
  before_filter :load_user

  before_filter :require_admin, only: [:edit, :index, :update, :new, :create]
  before_filter :correct_user, only: [:show]



  respond_to :html

  def index
    @assessments = @user.assessments.all
    respond_with(@assessments)
  end

  def show
    respond_with(@user, @assessment)
  end

  def new
    @assessment = @user.assessments.new
    @course_sessions = CourseSession.joins("join students_sessions on course_sessions.id = students_sessions.course_session_id").where("students_sessions.user_id = ?", @user.id)
    respond_with(@assessment)
  end

  def edit
  end

  def create
    @assessment = @user.assessments.new(assessment_params)
    @assessment.save
    UserMailer.create_assessment_email(@user, @assessment).deliver
    flash[:notice] = "Successfully created assessment and sent notification email"
    respond_with(@user, @assessment)
  end

  def update
    @assessment.update(assessment_params)
    respond_with(@assessment)
  end

  def destroy
    @assessment.destroy
    respond_with(@assessment)
  end

  private

    def load_user
      @user = User.find(params[:user_id])
    end


    def set_assessment
      @assessment = Assessment.find(params[:id])
    end

    def assessment_params
      params.require(:assessment).permit(:effort_grade, :effort_comments, :communication_grade, 
                                         :communication_comments, :eng_writing_grade, :eng_writing_comments, 
                                         :eng_speaking_grade, :eng_speaking_comments, :eng_reading_grade, 
                                         :eng_reading_comments, :crit_thinking_grade, :crit_thinking_comments, 
                                         :progress_grade, :progress_comments, :gen_comments, :user_id, 
                                         :course_session_id)
    end


end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/views/assessments/_form.html.erb
<%= simple_form_for([@user, @assessment]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
  	<%= f.association :course_session, :collection => @course_sessions, label_method: :full_title, :hint => "Leave blank if you're creating an assessment for the reading program" %>
  	<hr/>
  	<h4>Effort</h4>
  	<%= f.input :effort_grade, :label => "Grade:" %>
  	<%= f.input :effort_comments, :label => "Comments:" %>
    <hr/>
  	<h4>Manner and quality of communication with advisor</h4>
  	<%= f.input :communication_grade, :label => "Grade:" %>
  	<%= f.input :communication_comments, :label => "Comments:" %>
  	<hr/>
  	<h4>English Writing Level</h4>
  	<%= f.input :eng_writing_grade, :label => "Grade:" %>
  	<%= f.input :eng_writing_comments, :label => "Comments:" %>
 	<hr/>
  	<h4>English Speaking Level</h4>
  	<%= f.input :eng_speaking_grade, :label => "Grade:" %>
  	<%= f.input :eng_speaking_comments, :label => "Comments:" %> 	
  	<hr/>
  	<h4>English Reading Level</h4>
  	<%= f.input :eng_reading_grade, :label => "Grade:" %>
  	<%= f.input :eng_reading_comments, :label => "Comments:" %>
  	<hr/>
  	<h4>Critical thinking</h4>
  	<%= f.input :crit_thinking_grade, :label => "Grade:" %>
  	<%= f.input :crit_thinking_comments, :label => "Comments:" %>  	
  	<hr/>
  	<h4>Progress towards preparedness for college</h4>
  	<%= f.input :progress_grade, :label => "Grade:" %>
  	<%= f.input :progress_comments, :label => "Comments:" %>
  	<hr/>
  	<%= f.input :gen_comments, :label => "General Comments:" %>
  	
    <%= f.button :submit %>
  </div>
<% end %>

app/views/assessments/edit.html.erb
<h1>Editing assessment</h1>

<%= render 'form' %>

<%= link_to 'Show', @assessment %> |
<%= link_to 'Back', assessments_path %>

app/views/assessments/index.html.erb
<h1>Assessments: <%= @user.name %></h1>


<table id="table_responses" class="datatable-wide table table-striped table-bordered">
  <thead>
    <tr>
      <th> Course/Program </th>
      <th> Submitted </th>
    </tr>
  </thead>

  <tbody> 
    <% for a in @user.assessments %>
      <tr>
        <% if a.course_session.nil? %>
        <td> <%= link_to "Reading Program", books_path %></td>
        <% else %>
        <td> <%= link_to a.course_session.full_title, course_session_path(a.course_session) %></td>
        <% end %>
      <td> <%= link_to (a.created_at + 28800).strftime('%B %e, %Y %l:%M %p'), user_assessment_path(@user, a) %>
</td>
      <td> <%= link_to 'Destroy Assessment' , [a.user , a], method: :delete, data: { confirm: 'Are you sure you want to delete this assessment?' } %></td>
      <% end %>
      </tr>
  </tbody>
</table>

<br>

<%= link_to 'Add an assessment', new_user_assessment_path(@user) %>

app/views/assessments/new.html.erb
<h1>New assessment for <%= @user.name %></h1>

<%= render 'form' %>

<%= link_to 'Back', user_assessments_path %>

app/views/assessments/show.html.erb
<p id="notice"><%= notice %></p>

<% if @assessment.course_session.nil? %>
<h1><%= @user.name + ", Reading Program Assessment" %></h1>
<% else %>
<h1><%= @user.name + ", " + @assessment.course_session.full_title %></h1>
<% end %>



<div class="row">
	<div class="col-md-9">
	<div class="well">
		<ul>
		<dt>Submitted:  <%= (@assessment.created_at + 28800).strftime('%B %e, %Y %l:%M %p') %></dt>
		<hr/>
		<dt>Effort: <%= @assessment.effort_grade %></dt>
		<dd><%= @assessment.effort_comments%></dd>
		<hr/>
		<dt>Manner and quality of communication with advisor: <%= @assessment.communication_grade %></dt>
		<dd><%= @assessment.communication_comments%></dd>
		<hr/>		
		<dt>English Writing Level: <%= @assessment.eng_writing_grade %></dt>
		<dd><%= @assessment.eng_writing_comments%></dd>
		<hr/>		
		<dt>English Speaking Level: <%= @assessment.eng_speaking_grade %></dt>
		<dd><%= @assessment.eng_speaking_comments%></dd>
		<hr/>		
		<dt>English Reading Level: <%= @assessment.eng_reading_grade %></dt>
		<dd><%= @assessment.eng_reading_comments%></dd>
		<hr/>		
		<dt>Critical thinking: <%= @assessment.crit_thinking_grade %></dt>
		<dd><%= @assessment.crit_thinking_comments%></dd>
		<hr/>
		<dt>Progress towards preparedness for college: <%= @assessment.progress_grade %></dt>
		<dd><%= @assessment.progress_comments%></dd>
		<hr/><dt>Other Comments: </dt>
		<dd><%= @assessment.gen_comments%></dd>
		<hr/>

		</ul>
	</div>
	</div>

	<div class="col-md-3">
	<div class="well">
	 <h4>Past assessments</h4>
	 <% if @user.assessments.nil? %>
	 	(none)
	 <% else %>
	    <% @user.assessments.each do |a| %>
	    <%= link_to (a.created_at + 28800).strftime('%B %e, %Y %l:%M %p'), user_assessment_path(@user, a) %>
	    <% end %>
	 <% end %>


	</div>
</div>


</div>

<% if current_user.is_admin? %>
<%= link_to 'Edit Assessment', edit_user_assessment_path(@user, @assessment) %> 
<%= link_to 'All Assessments', user_assessments_path %>
<% end %>