config/routes.rb
Rails.application.routes.draw do

  resources :article_sources

  resources :course_assignments do
    resources :assignment_responses
  end

  resources :course_periods
  get 'academic_terms' => 'course_periods#index'

  resources :course_sessions  do  
    resources :course_meetings
  end

  get 'my_sessions' => 'course_sessions#my_course_sessions', :as => :my_sessions

  resources :course_categories
  resources :courses

  resources :course_packets
  get 'resources' => 'course_packets#resources'  

  resources :discussion_questions do
      resources :discussion_responses
  end 
  
  resources :books do
    member do
      get :questions
    end
  end
  get 'index_table' => 'books#index_table', :as => :index_table

  resources :articles

  resources :book_categories
  get 'categories_table' => 'book_categories#table_index', :as => :categories_table

  resources :book_lists,       only: [:create, :destroy]
  resources :article_lists,       only: [:create, :destroy]
  resources :read_books,       only: [:create, :destroy]

  resources :users
  get 'register'  => 'users#new'
  get 'student_list' => 'users#student_list', :as => :student_list  
  get 'admin_list' => 'users#admin_list', :as => :admin_list
  get 'alumni_list' => 'users#alumni_list', :as => :alumni_list

  get 'my_courses' => 'users#course_list', :as => :my_courses

  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :account_activations, only: [:edit]

  resources :password_resets

  resources :users do
    resources :assessments
    member do
      get :following, :followers
      get :book_responses
      get :article_responses
      get 'my_instructors' => "users#my_instructor_list", :as => :my_instructors
      get 'my_students' => "users#my_student_list", :as => :my_students
      get 'books' => 'users#user_books', :as => :books
      get 'articles' => 'users#user_articles', :as => :articles
      get :edit_profile
      put :update_profile
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :advisor_relationships,       only: [:create, :destroy]

 resources :users do
    member do
      get :activate
    end
  end

  get '/about'    => 'high_voltage/pages#show', id: 'about'
  get '/contact'  => 'high_voltage/pages#show', id: 'contact'
  get '/privacy'  => 'high_voltage/pages#show', id: 'privacy'
  get '/terms'    => 'high_voltage/pages#show', id: 'terms'
  get '/team'    => 'high_voltage/pages#show', id: 'team'
  get '/student_portal'    => 'high_voltage/pages#show', id: 'student_portal'
  get '/admin_portal'    => 'high_voltage/pages#show', id: 'admin_portal'
  get '/community' => 'high_voltage/pages#show', id: 'community'
  get '/policies' => 'high_voltage/pages#show', id: 'policies'
  get '/zoom' => 'high_voltage/pages#show', id: 'zoom'
  get '/zoom_tour' => 'high_voltage/pages#show', id: 'zoom_tour'
  get '/zoom_tips' => 'high_voltage/pages#show', id: 'zoom_tips'

  get '/home', to: redirect('/')
  root :to => 'high_voltage/pages#show', id: 'home'

  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

app/models/article.rb
class Article < ActiveRecord::Base

	validates_presence_of :title, :author, :article_source_id



	belongs_to :article_source

	has_many :discussion_questions

  has_many :article_lists, dependent: :destroy
  has_many :watchers, through: :article_lists, class_name: "User", foreign_key: "watcher_id"



  	def full_title
     [title, article_source.title].join(", ")
  	end


	#creating the attachment
	has_attached_file :attachment 

    validates_attachment_content_type :attachment, :content_type => ['application/pdf', 'application/msword', 'text/plain']
    validates_with AttachmentSizeValidator, :attributes => :attachment, :less_than => 10.megabytes

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]


  before_filter :require_login
  before_filter :require_admin, only: [:edit, :new]
  before_filter :set_articles

  respond_to :html

  def index
    @articles = Article.all
    respond_with(@articles)
  end

  def show
    #respond_with(@article)
    @article = Article.find(params[:id])
    @questions = @article.discussion_questions.all.sort_by { |q| [ q.week_number ] }
  end

  def new
    @article = Article.new
    respond_with(@article)
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.save
    respond_with(@article)
  end

  def update
    @article.update(article_params)
    respond_with(@article)
  end

  def destroy
    @article.destroy
    respond_with(@article)
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :author, :source, :url, :category, :published, 
                                      :description, :word_count, :level, :article_source_id, 
                                      :attachment)    
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :title %>
    <%= f.input :author %>
    <%= f.association :article_source, :label => "Source" %>
    <%= f.input :description %>
    <%= f.input :url, :label => "URL" %>
    <%= f.input :attachment %>
    <%= f.input :word_count %>
    <%= f.input :level, :label => "Reading Level" %>
    <%= f.input :category %>
    <%= f.input :published, as: :date, start_year: Date.today.year - 30,
                              end_year: Date.today.year%>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Article Directory</h1>

<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <a href="https://app.mindimp.com/articles/22">
      <img src="http://i.imgur.com/ltS393G.jpg" alt="...">
    </a>
      <div class="carousel-caption">
        <h3>"The Real Problem With College Admissions: It's Not the Rankings"</h3>
        <p>The Atlantic </p>
      </div>
    </div>
    <div class="item">
      <a href="https://app.mindimp.com/articles/29">
      <img src="http://i.imgur.com/UUqR9wb.jpg" alt="...">
    </a>
      <div class="carousel-caption">
        <h3>"The Red Cross' Secret Disaster"</h3>
        <p>ProPublica</p>
      </div>
    </div>
    <div class="item">
      <a href="https://app.mindimp.com/articles/26">
      <img src="http://i.imgur.com/IlsGfdl.jpg" alt="...">
      </a>
      <div class="carousel-caption">
        <h3>"The Ebola Wars"</h3>
        <p>The New Yorker</p>
      </div>
    </div>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div> <!-- Carousel -->

<hr/>





<table id="table_articles" class="datatable-wide table table-striped table-bordered">
  <thead>
  <tr>
    <th>Title </th>
    <th>Author</th>
    <th>Source </th>
    <th>Category</th>
    <th>Reading Level</th>

  </tr>
  </thead>
  <tbody>
  <% for article in @articles %>
    <td><%= link_to article.title, article %></td>
    <td><%= link_to article.author, article %></td> 
    <% if article.article_source.nil? %> 
    <td><%= link_to "(no source)", article %></td>
      <% else %>
    <td><%= link_to article.article_source.title, article %></td>
    <% end %>
    <td><%= link_to article.category, article %></td> 
    <% unless article.level.nil? %>
    <td> <%= link_to article.level, article %></td> 
    <% end %>
    </tr>
  <% end %>
</tbody>
</table>


<br>

<% if current_user.is_admin? %>
  <%= link_to "Add a New Article", new_article_path, :class => "btn" %>
  <%= link_to "Add a New Article Source", new_article_source_path, :class => "btn" %>
<% end %>

app/views/articles/new.html.erb
<h1>Add an article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<% if @article.article_source.nil? %>
<h1><%= @article.title %>, (no source)</h1>
<% else %>
<h1><%= @article.full_title %></h1>
<% end %>


<div class="row">
    <div class="col-md-8">

    	<h4><dd><%= @article.description %></dd></h4>

        <%= render "users/article_form" %>
<hr/>


        <div class="well">
       	<h2>Discussion Questions: </h2>
        <% if @questions.nil? && current_user.is_admin? %>
         <p>There don't seem to be any discussion questions, would you like to add some? </p>
         <%= link_to "New Discussion Question", new_discussion_question_path, class: "btn btn-info"%>
        <% elsif @questions.nil? %>
          There are no discussion questions for this article. 
        <% else %>
        <ol>
        <% @questions.each do |q|%>
         <li> <%= link_to q.question, discussion_question_path(q) %> </li>
         <dt><%= link_to "Respond", new_discussion_question_discussion_response_path(q)%> </dt>
         <% if current_user.is_admin?%> 
            <%= link_to "Edit Question", edit_discussion_question_path(q) %> | 
            <%= link_to 'Delete Question', q, method: :delete, data: { confirm: 'Are you sure?' } %> |  
            <%=link_to "View all responses", discussion_question_discussion_responses_path(q) %>
         <% end %>
         <% end %>
        </ol>
        <% end %>
     	</div>
     </div>

   	<div class="col-md-4">
       <div class="well">
        <dt>Author: </dt>
        <dd><%= @article.author %></dd>
        <dt>Source: </dt>
        <% if @article.article_source.nil? %>
            <dd>(none)</dd>
        <% else %>
            <dd><%= link_to @article.article_source.title, article_source_path(@article.article_source) %></dd>
        <% end %>
        <dt>Date of Publication: </dt>
        <dd><%= (@article.published + 28800).strftime('%B %e, %Y')%></dd>
        <dt>Word Count: </dt>
        <dd><%= @article.word_count %></dd>
        <dt>Reading Level: </dt>
        <dd><%= @article.level %></dd><hr />
        <p><%= link_to "Read Article", @article.url, class: "btn btn-info", :target => "_blank" %></p>
        <p><%= link_to "Download Article", @article.attachment.url, target: "_blank", class: "btn btn-info" %></p>

       </div>
    
	</div>
</div>


<% if current_user.is_admin? %>
<%= link_to 'New Discussion Question', new_discussion_question_path %> | 
<%= link_to 'Edit Article', edit_article_path(@article) %> | 
<%= link_to 'Destroy Article', @article, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %></br>
<%= link_to 'Back to Articles', articles_path, :class => "btn btn-lg" %>