config/routes.rb
Rails.application.routes.draw do

  resources :article_sources

  resources :course_assignments do
    resources :assignment_responses
  end

  resources :course_periods
  get 'academic_terms' => 'course_periods#index'

  resources :course_sessions  do  
    resources :course_meetings
  end

  get 'my_sessions' => 'course_sessions#my_course_sessions', :as => :my_sessions

  resources :course_categories
  resources :courses

  resources :course_packets
  get 'resources' => 'course_packets#resources'  

  resources :discussion_questions do
      resources :discussion_responses
  end 
  
  resources :books do
    member do
      get :questions
    end
  end
  get 'index_table' => 'books#index_table', :as => :index_table

  resources :articles

  resources :book_categories
  get 'categories_table' => 'book_categories#table_index', :as => :categories_table

  resources :book_lists,       only: [:create, :destroy]
  resources :article_lists,       only: [:create, :destroy]
  resources :read_books,       only: [:create, :destroy]

  resources :users
  get 'register'  => 'users#new'
  get 'student_list' => 'users#student_list', :as => :student_list  
  get 'admin_list' => 'users#admin_list', :as => :admin_list
  get 'alumni_list' => 'users#alumni_list', :as => :alumni_list

  get 'my_courses' => 'users#course_list', :as => :my_courses

  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :account_activations, only: [:edit]

  resources :password_resets

  resources :users do
    resources :assessments
    member do
      get :following, :followers
      get :book_responses
      get :article_responses
      get 'my_instructors' => "users#my_instructor_list", :as => :my_instructors
      get 'my_students' => "users#my_student_list", :as => :my_students
      get 'books' => 'users#user_books', :as => :books
      get 'articles' => 'users#user_articles', :as => :articles
      get :edit_profile
      put :update_profile
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :advisor_relationships,       only: [:create, :destroy]

 resources :users do
    member do
      get :activate
    end
  end

  get '/about'    => 'high_voltage/pages#show', id: 'about'
  get '/contact'  => 'high_voltage/pages#show', id: 'contact'
  get '/privacy'  => 'high_voltage/pages#show', id: 'privacy'
  get '/terms'    => 'high_voltage/pages#show', id: 'terms'
  get '/team'    => 'high_voltage/pages#show', id: 'team'
  get '/student_portal'    => 'high_voltage/pages#show', id: 'student_portal'
  get '/admin_portal'    => 'high_voltage/pages#show', id: 'admin_portal'
  get '/community' => 'high_voltage/pages#show', id: 'community'
  get '/policies' => 'high_voltage/pages#show', id: 'policies'
  get '/zoom' => 'high_voltage/pages#show', id: 'zoom'
  get '/zoom_tour' => 'high_voltage/pages#show', id: 'zoom_tour'
  get '/zoom_tips' => 'high_voltage/pages#show', id: 'zoom_tips'

  get '/home', to: redirect('/')
  root :to => 'high_voltage/pages#show', id: 'home'

  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

app/models/article_source.rb
class ArticleSource < ActiveRecord::Base

	validates_presence_of :title

	has_many :articles, dependent: :nullify

	has_attached_file :photo,
                 	  :styles => { :medium => "300x300>", :thumb => "50x50>" }, 
                      :default_url => "/images/:style/article_missing.jpeg"
                      # :storage => :s3

  validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, :attributes => :photo, :less_than => 1.megabytes



end

app/controllers/article_sources_controller.rb
class ArticleSourcesController < ApplicationController
  before_action :set_article_source, only: [:show, :edit, :update, :destroy]


  before_filter :require_login
  before_filter :require_admin, only: [:edit, :new]
  before_filter :set_articles

  respond_to :html

  def index
    @article_sources = ArticleSource.all
    respond_with(@article_sources)
  end

  def show
    respond_with(@article_source)
  end

  def new
    @article_source = ArticleSource.new
    respond_with(@article_source)
  end

  def edit
  end

  def create
    @article_source = ArticleSource.new(article_source_params)
    @article_source.save
    respond_with(@article_source)
  end

  def update
    @article_source.update(article_source_params)
    respond_with(@article_source)
  end

  def destroy
    @article_source.destroy
    respond_with(@article_source)
  end

  private
    def set_article_source
      @article_source = ArticleSource.find(params[:id])
    end

    def article_source_params
      params.require(:article_source).permit(:title, :description, :url, :photo)
    end
end

app/helpers/article_sources_helper.rb
module ArticleSourcesHelper
end

app/views/article_sources/_form.html.erb
<%= simple_form_for(@article_source) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
  	<%= f.input :title %>
  	<%= f.input :description %>
  	<%= f.input :url %>
  	<%= f.input :photo %>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/article_sources/edit.html.erb
<h1>Editing article_source</h1>

<%= render 'form' %>

<%= link_to 'Show', @article_source %> |
<%= link_to 'Back', article_sources_path %>

app/views/article_sources/index.html.erb
<h1>MindImp Article Sources</h1>

<div class="row">
<% @article_sources.each do |a| %>
   <div class="col-xs-6 col-md-3">
        <div class="thumbnail">
        <%= image_tag a.photo.url(:medium) %>
        <dt><%= link_to a.title, article_source_path(a)%></dt>
        </div>  
        <br/><br/>
  
      </div>
<% end %>
</div>




<% if current_user.is_admin? %>
<%= link_to 'Add an Article source', new_article_source_path %>
<% end %>

app/views/article_sources/new.html.erb
<h1>New Article Source</h1>

<%= render 'form' %>

<%= link_to 'Back to Articles', articles_path, :class => "btn btn-lg" %>

app/views/article_sources/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @article_source.title %></h1>
<blockquote class="blockquote-reverse"><%= @article_source.description %></blockquote>
<blockquote class="blockquote-reverse"><%= link_to @article_source.url, "http://#{@article_source.url}", target: "_blank" %></blockquote>


<div class="row">
	<div class="col-md-4">
		<div class="thumbnail">
		<%= image_tag @article_source.photo(:medium) %>
		</div>
	</div>
	<div class="col-md-8">
		<div class="well">
			<% @article_source.articles.each do |a| %>
			<div class="well"><%= link_to a.title, article_path(a) %></div>
			<% end %>
		</div>
	</div>
</div>



<hr/>
<% if current_user.is_admin? %>
<%= link_to 'Edit Article Source', edit_article_source_path(@article_source), :class => "btn btn-lg" %> | 
<%=link_to 'Destroy Article Source', @article_source, method: :delete, data: { confirm: 'Are you sure? This will disassociate all associated articles.' }, :class => "btn btn-lg" %>
<% end %>
<%= link_to 'Back to Articles', articles_path, :class => "btn btn-lg" %>
<%= link_to 'Back to Sources', article_sources_path, :class => "btn btn-lg" %>