config/routes.rb
Rails.application.routes.draw do

  resources :article_sources

  resources :course_assignments do
    resources :assignment_responses
  end

  resources :course_periods
  get 'academic_terms' => 'course_periods#index'

  resources :course_sessions  do  
    resources :course_meetings
  end

  get 'my_sessions' => 'course_sessions#my_course_sessions', :as => :my_sessions

  resources :course_categories
  resources :courses

  resources :course_packets
  get 'resources' => 'course_packets#resources'  

  resources :discussion_questions do
      resources :discussion_responses
  end 
  
  resources :books do
    member do
      get :questions
    end
  end
  get 'index_table' => 'books#index_table', :as => :index_table

  resources :articles

  resources :book_categories
  get 'categories_table' => 'book_categories#table_index', :as => :categories_table

  resources :book_lists,       only: [:create, :destroy]
  resources :article_lists,       only: [:create, :destroy]
  resources :read_books,       only: [:create, :destroy]

  resources :users
  get 'register'  => 'users#new'
  get 'student_list' => 'users#student_list', :as => :student_list  
  get 'admin_list' => 'users#admin_list', :as => :admin_list
  get 'alumni_list' => 'users#alumni_list', :as => :alumni_list

  get 'my_courses' => 'users#course_list', :as => :my_courses

  resources :user_sessions
  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  resources :account_activations, only: [:edit]

  resources :password_resets

  resources :users do
    resources :assessments
    member do
      get :following, :followers
      get :book_responses
      get :article_responses
      get 'my_instructors' => "users#my_instructor_list", :as => :my_instructors
      get 'my_students' => "users#my_student_list", :as => :my_students
      get 'books' => 'users#user_books', :as => :books
      get 'articles' => 'users#user_articles', :as => :articles
      get :edit_profile
      put :update_profile
    end
  end
  resources :relationships,       only: [:create, :destroy]
  resources :advisor_relationships,       only: [:create, :destroy]

 resources :users do
    member do
      get :activate
    end
  end

  get '/about'    => 'high_voltage/pages#show', id: 'about'
  get '/contact'  => 'high_voltage/pages#show', id: 'contact'
  get '/privacy'  => 'high_voltage/pages#show', id: 'privacy'
  get '/terms'    => 'high_voltage/pages#show', id: 'terms'
  get '/team'    => 'high_voltage/pages#show', id: 'team'
  get '/student_portal'    => 'high_voltage/pages#show', id: 'student_portal'
  get '/admin_portal'    => 'high_voltage/pages#show', id: 'admin_portal'
  get '/community' => 'high_voltage/pages#show', id: 'community'
  get '/policies' => 'high_voltage/pages#show', id: 'policies'
  get '/zoom' => 'high_voltage/pages#show', id: 'zoom'
  get '/zoom_tour' => 'high_voltage/pages#show', id: 'zoom_tour'
  get '/zoom_tips' => 'high_voltage/pages#show', id: 'zoom_tips'

  get '/home', to: redirect('/')
  root :to => 'high_voltage/pages#show', id: 'home'

  %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  before_filter :require_admin, only: [:edit, :new]
  before_filter :set_courses, except: [:index, :show]


  respond_to :html

  def index
    @courses = Course.all
    respond_with(@courses)
  end

  def show
    respond_with(@course)
  end

  def new
    @course = Course.new
    respond_with(@course)
  end

  def edit
  end

  def create
    @course = Course.new(course_params)
    @course.save
    respond_with(@course)
  end

  def update
    @course.update(course_params)
    respond_with(@course)
  end

  def destroy
    @course.destroy
    respond_with(@course)
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:title, :abbreviation, :description, :syllabus, :session_no, :course_category_id, :book_category_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= simple_form_for(@course) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
  	<%= f.input :title %>
    <%= f.input :abbreviation %>
    <%= f.input :description %>
    <%= f.input :syllabus, :label => "Syllabus", :hint => "Please attach a PDF" %>
    <%= f.association :course_category, :label => "Subject Area" %>
    <%= f.input :session_no, :label => "Number of Weeks" %>
    <%= f.association :book_category, :label => "Book List", :hint => "(Optional)" %>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing "<%= @course.title %>"</h1>

<%= render 'form' %>


<% if current_user.is_admin? %>
<%= link_to 'Show', @course %> 
<% end %>
</br>
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Courses</h1>


<table id="table_courses" class="datatable-wide table table-striped table-bordered">
  <thead>
    <tr>
      <th>Title </th>
      <th>Abbreviation</th>
      <th>Description </th>
    </tr>
  </thead>
  <tbody>
  <% for course in @courses %>
    <td><%= link_to course.title, course %></td>
    <td><%= link_to course.abbreviation, course %></td>    
    <td><%= link_to course.description, course %></td>
  </tr>
  <% end %>
  </tbody>
</table>


<br>

<% if current_user.is_admin? %>
<%= link_to 'Add a New Course', new_course_path %>
<% end %> 


<script>
$('.table_courses').DataTable({
</script>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%=  @course.abbreviation + ": " + @course.title %></h1>

<div class="row">
    <div class="col-md-8">
        <div class="well">
            <dt>Description: </dt>
            <dd><%= @course.description %></dd>
            <dt> Subject Area: </dt>
            <dd><%= link_to @course.course_category.title, course_category_path(@course.course_category) %></dd>
        </div>
        <div class="well">
            <% unless @course.book_category.nil? %>
            <% @course.book_category.books.each do |b| %>
            <%= image_tag b.cover(:thumb) %>
            <%= link_to b.title, b %>
            <% end %>
            <% else %>
            There is no book list for this class.
            <% end %>
        </div>
        <div class="well">
            <% if !@course.course_packets.nil? %>
            <% @course.course_packets.each do |p| %>
            <%= link_to p.title, p %>
                <ul><% p.course_files.each do |f|%>
                <li><%= link_to f.title, f.image.url, target: "_blank" %></li>
                <% end %>
                </ul>
            <% end %>
            <% else %>
            There is no book list for this class.
            <% end %>
        </div>
    </div>
    <div class="col-md-4">
        <div class="well">
        <dt> Class Duration: </dt>
        <dd><%= @course.session_no %> weeks</dd>
        <dt>Syllabus:</dt>
        <% unless @course.syllabus.nil? %>
            <dd><%= link_to "Download here", @course.syllabus.url, target: "_blank" %></dd>
        <% else %>
            <dd>There is no syllabus available for this class. </dd>
        <% end %>
    	</div>
        <%if current_user.is_admin? %>
        <div class="well">
        <dt> Current Sessions: </dt>
        <% unless @course.course_sessions.empty? %>
            <% @course.course_sessions.where(active: true).each do |c| %>
            <dd><%= link_to c.title, course_session_path(c)%> </dd>
            <% end %>
        <% else %> 
            <dd>(none)</dd> 
        <% end %>
        </div>
        <% end %>
    </div>
    
</div>


<% if current_user.is_admin? %>
<%= link_to "Add a Course Session", new_course_session_path %> |
<%= link_to "Add a Course Packet", new_course_packet_path %>
</br>
<%= link_to 'Edit Course', edit_course_path(@course) %>   |   
<%= link_to 'Destroy Course', @course, method: :delete, data: { confirm: 'Are you sure you want to delete this course? This will delete all associated course sessions and this action is irreversible.' } %>
<% end %>
</br>
<%= link_to 'All Courses', courses_path, :class => "btn" %>